apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-orchestrator
  description: Distributed payment processing with PSP failover
  annotations:
    vault.io/psp-credentials: payment-secrets-v3
    sentry.io/project: payment-errors
    backstage.io/techdocs-ref: dir:./payment-system
    example.com/arch-decision: "ADR-001"
  links:
    - url: https://api-docs.example.com/payments
      title: API Documentation
      icon: api
  tags: [java, stripe, paypal]
spec:
  type: service
  lifecycle: production
  owner: payments-team
  system: payment-system
  providesApis: [payment-api]
  consumesApis: [fraud-api]
  dependencies:
    - component: fraud-detector
      type: dependsOn
    - component: order-orchestrator
      type: dependsOn
    - component: cart-service
      type: dependsOn
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: payment-system
  description: Payment processing and orchestration system
spec:
  owner: payments-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: order-system
  description: Order management and fulfillment system
spec:
  owner: orders-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: cart-system
  description: Shopping cart and checkout system
spec:
  owner: checkout-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: inventory-system
  description: Warehouse and inventory management system
spec:
  owner: logistics-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: payments-team
  description: Payments engineering team
spec:
  type: team
  profile:
    displayName: Payments Team
    email: payments-team@example.com
  members:
    - user: alice
    - user: bob
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: orders-team
  description: Order management team
spec:
  type: team
  profile:
    displayName: Orders Team
    email: orders-team@example.com
  members:
    - user: charlie
    - user: dave
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: checkout-team
  description: Checkout and cart service team
spec:
  type: team
  profile:
    displayName: Checkout Team
    email: checkout-team@example.com
  members:
    - user: eve
    - user: frank
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: logistics-team
  description: Logistics and warehouse management team
spec:
  type: team
  profile:
    displayName: Logistics Team
    email: logistics-team@example.com
  members:
    - user: grace
    - user: hank
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: data-team
  description: Data science and analytics team
spec:
  type: team
  profile:
    displayName: Data Team
    email: data-team@example.com
  members:
    - user: isaac
    - user: jack
