apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-orchestrator
  description: Distributed payment processing with PSP failover
  annotations:
    vault.io/psp-credentials: payment-secrets-v3
    sentry.io/project: payment-errors
    backstage.io/techdocs-ref: dir:./payment-system
    example.com/arch-decision: "ADR-001"
  links:
    - url: https://api-docs.example.com/payments
      title: API Documentation
      icon: api
  tags: [java, stripe, paypal]
spec:
  type: service
  lifecycle: production
  owner: payments-team
  system: payment-system
  providesApis: [payment-api]
  consumesApis: [fraud-api]
  dependencies:
    - component: fraud-detector
      type: dependsOn
    - component: order-orchestrator
      type: dependsOn
    - component: cart-service
      type: dependsOn
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: content-system
  description: Content management system for the organization
spec:
  owner: content-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: content-team
  description: Content team responsible for CMS and marketing tools
spec:
  type: team
  profile:
    displayName: Content Team
    email: content-team@example.com
  members:
    - user: alice
    - user: bob
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fraud-detector
  description: Real-time transaction risk analysis using ML
  annotations:
    sagemaker/model: fraud-model-v5
    kafka/topic: transactions-raw
    backstage.io/techdocs-ref: dir:./fraud-detector
  tags: [python, tensorflow, fintech]
spec:
  type: service
  lifecycle: production
  owner: security-team
  system: payment-system
  providesApis: [fraud-api]
  dependencies:
    - component: payment-orchestrator
      type: provides
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-orchestrator
  description: Distributed transaction coordinator for orders
  annotations:
    temporal/workflow: order-fulfillment
    redis/instance: order-state-01
    backstage.io/techdocs-ref: dir:./order-system
  tags: [c#, saga-pattern]
spec:
  type: service
  lifecycle: production
  owner: orders-team
  system: order-system
  dependencies:
    - component: payment-orchestrator
      type: dependsOn
    - component: inventory-sync
      type: dependsOn
    - component: fraud-detector
      type: dependsOn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cart-service
  description: Distributed shopping cart with Redis caching
  annotations:
    redis/instance: cart-cluster-01
    newrelic/apm: cart-service
    backstage.io/techdocs-ref: dir:./cart-service
  tags: [nodejs, redis]
spec:
  type: service
  lifecycle: production
  owner: checkout-team
  system: cart-system
  dependencies:
    - component: inventory-sync
      type: dependsOn
    - component: payment-orchestrator
      type: dependsOn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recommendation-engine
  description: AI-powered product recommendations
  annotations:
    vertex-ai/model: recos-2024q2
    bigquery/dataset: user-behavior
    backstage.io/techdocs-ref: dir:./recommendations
  tags: [python, pytorch]
spec:
  type: service
  lifecycle: production
  owner: data-team
  system: personalization
  consumesApis: [product-api]
  dependencies:
    - component: product-api
      type: dependsOn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-sync
  description: Real-time warehouse inventory synchronization
  annotations:
    aws/eventbridge: inventory-events
    warehouse/erp: sap-s4hana
    backstage.io/techdocs-ref: dir:./inventory
  tags: [go, kafka, aws]
spec:
  type: service
  lifecycle: production
  owner: logistics-team
  system: inventory-system
  consumesApis: [erp-api]
  dependencies:
    - component: erp-adapter
      type: dependsOn
    - component: order-orchestrator
      type: dependsOn
