apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-vm-provision
  title: AWS VM Provisioning Template
  description: >
    A professional template to provision an AWS Virtual Machine.
    This template collects configuration details and then triggers a Rundeck job
    to create the VM using an authenticated PI token.
spec:
  type: template
  owner: default
  parameters:
    type: object
    required:
      - vmName
      - region
      - instanceType
      - amiId
      - keyPairName
      - rundeckJobId
      - piToken
    properties:
      vmName:
        title: VM Name
        type: string
        description: The name to assign to the AWS Virtual Machine.
        default: my-aws-vm
      region:
        title: AWS Region
        type: string
        description: The AWS region where the VM will be provisioned.
        enum:
          - us-east-1
          - us-west-2
          - eu-west-1
          - ap-southeast-1
        default: us-east-1
      instanceType:
        title: Instance Type
        type: string
        description: The AWS instance type for the Virtual Machine.
        enum:
          - t2.micro
          - t2.small
          - t3.medium
          - m5.large
        default: t2.micro
      amiId:
        title: AMI Identifier
        type: string
        description: The Amazon Machine Image (AMI) identifier to use.
        default: ami-0abcdef1234567890
      keyPairName:
        title: Key Pair Name
        type: string
        description: The AWS key pair name for SSH access.
        default: my-keypair
      rundeckJobId:
        title: Rundeck Job Identifier
        type: string
        description: The Rundeck job ID that triggers the AWS VM provisioning.
        default: AWS_VM_PROVISION_JOB_ID
      piToken:
        title: Personal API Token
        type: string
        description: The PI token used for authentication with the Rundeck endpoint.
  steps:
    - id: trigger-aws-vm-provision
      name: Trigger AWS VM Provisioning
      action: http:post
      input:
        url: "https://rundeck.example.com/api/14/job/{{ parameters.rundeckJobId }}/run"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ parameters.piToken }}"
        body:
          vmName: "{{ parameters.vmName }}"
          region: "{{ parameters.region }}"
          instanceType: "{{ parameters.instanceType }}"
          amiId: "{{ parameters.amiId }}"
          keyPairName: "{{ parameters.keyPairName }}"
