apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-vm-provision
  title: PagerDuty On Tour 25 Provisioning
  description: >
    Professional template to provision AWS VMs through Rundeck automation
spec:
  owner: infrastructure-team@yourcompany.com
  parameters:
    - title: AWS Configuration
      required:
        - vmName
        - region
        - instanceType
        - amiId
        - keyPairName
      properties:
        vmName:
          title: VM Name
          type: string
          description: Unique name for the EC2 instance
          ui:autofocus: true
        region:
          title: AWS Region
          type: string
          enum: [us-east-1, us-west-2, eu-west-1, ap-southeast-1]
          default: us-east-1
          description: Target deployment region
        instanceType:
          title: Instance Type
          type: string
          enum: [t2.micro, t2.small, t3.medium, m5.large]
          default: t2.micro
          description: EC2 instance class
        amiId:
          title: AMI ID
          type: string
          description: Base machine image identifier
          default: ami-0abcdef1234567890
        keyPairName:
          title: SSH Key Pair
          type: string
          description: AWS key pair for SSH access
          default: production-keypair

  steps:
    - id: execute-rundeck-job
      name: Provision VM via Rundeck
      action: rundeck:execute
      input:
        # Get from app-config.yaml instead of parameters
        endpoint: "{{ config('rundeck.endpoint') }}"
        authKey: "{{ config('rundeck.authKey') }}"
        jobId: "aws-ec2-provision"  # Fixed job ID from Rundeck
        parameters:
          vmName: "{{ parameters.vmName }}"
          region: "{{ parameters.region }}"
          instanceType: "{{ parameters.instanceType }}"
          amiId: "{{ parameters.amiId }}"
          keyPairName: "{{ parameters.keyPairName }}"

  output:
    links:
      - title: Rundeck Execution
        url: "{{ steps.execute-rundeck-job.output.executionUrl }}"
      - title: AWS Console
        url: "https://{{ parameters.region }}.console.aws.amazon.com/ec2"
