apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rundeck-job-template
  title: Execute Rundeck Job
  description: Executes a predefined Rundeck job with parameters
spec:
  owner: rundeck-team
  type: service
  parameters:
    - title: Rundeck Job Details
      required:
        - jobId
        - projectName
      properties:
        jobId:
          title: Job ID
          type: string
          description: The Rundeck Job ID to execute
        projectName:
          title: Project Name
          type: string
          description: The Rundeck Project Name
        environment:
          title: Environment
          type: string
          enum: ['dev', 'staging', 'prod']
        customParam:
          title: Custom Parameter
          type: string
          description: A custom parameter to pass to the job

  steps:
    - id: execute-rundeck
      name: Execute Rundeck Job
      action: rundeck:execute
      input:
        jobId: ${{ parameters.jobId }}
        projectName: ${{ parameters.projectName }}
        parameters:
          env: ${{ parameters.environment }}
          custom: ${{ parameters.customParam }}
        waitForCompletion: true
