apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-world-2
  title: Hello World 2
  description: scaffolder Hello, World template demo
spec:
  owner: backstage/techdocs-core
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Name of new project
          ui:autofocus: true
          ui:options:
            rows: 5
steps:
  - id: execute-runbook
    name: Execute Runbook
    action: http:backstage:request
    input:
      method: 'POST'
      path: '/proxy/rundeck'
      headers:
        'Content-Type': 'application/json'
        'X-Auth-Token': ${{ secrets.RUNDECK_AUTH_TOKEN }}
      body:
        option1: ${{ parameters.option1 }}
        option2: ${{ parameters.option2 }}
