apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rundeck-job-template
  title: Execute Rundeck Job
  description: Execute a job in Rundeck with parameters
  tags:
    - rundeck
    - job
    - automation
spec:
  owner: user:guest
  type: service
  
  parameters:
    - title: Rundeck Job Details
      required:
        - jobId
        - projectName
      properties:
        jobId:
          title: Job ID
          type: string
          description: The Rundeck job ID to execute
          ui:field: TextArea
        projectName:
          title: Project Name
          type: string
          description: The Rundeck project name
        environment:
          title: Environment
          type: string
          description: Target environment for the job
          enum:
            - dev
            - staging
            - prod
        region:
          title: Region
          type: string
          description: Target AWS region
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
        waitForJob:
          title: Wait for completion
          type: boolean
          description: Wait for job to complete before finishing
          default: true

  steps:
    - id: rundeck-execute
      name: Execute Rundeck Job
      action: rundeck:job:execute
      input:
        jobId: ${{ parameters.jobId }}
        projectName: ${{ parameters.projectName }}
        parameters:
          ENV: ${{ parameters.environment }}
          REGION: ${{ parameters.region }}
        waitForJob: ${{ parameters.waitForJob }}

  output:
    links:
      - title: Rundeck Execution
        url: ${{ steps['rundeck-execute'].output.executionId }}
        icon: dashboard
