apiVersion: backstage.io/v1beta3
kind: Template
metadata:
  name: run-rundeck-job
  title: Run Rundeck Job Template
spec:
  owner: your-team
  type: service
  steps:
    - id: run-rundeck-job
      name: Run Rundeck Job
      action: rundeck:job:run
      input:
        rundeckUrl: "https://rundeck.example.com"
        jobId: "your-job-id"
        apiToken: "your-api-token"
        parameters:
          param1: "value1"
          param2: "value2"
