apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rundeck-job-template
  title: Execute Rundeck Job
spec:
  owner: user:guest
  type: service
  
  parameters:
    - title: Rundeck Job Details
      required:
        - jobId
        - projectName
      properties:
        jobId:
          title: Job ID
          type: string
          description: The Rundeck Job ID to execute
        projectName:
          title: Project Name
          type: string
          description: The Rundeck Project Name
        parameters:
          title: Job Parameters
          type: object
          description: Parameters to pass to the Rundeck job
  
  steps:
    - id: execute-rundeck
      name: Execute Rundeck Job
      action: rundeck:execute
      input:
        jobId: ${{ parameters.jobId }}
        projectName: ${{ parameters.projectName }}
        parameters: ${{ parameters.parameters }}
        waitForCompletion: true
