apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rundeck-job-template
  title: Deploy AWS Resources
  description: Use this to deploy EC2 Host Resources
  tags:
    - rundeck
    - job
    - automation
spec:
  owner: user:guest
  type: service
  
  parameters:
    - title: Deploy Multicloud Resources
      required:
        - jobId
        - projectName
      properties:
        environment:
          title: Environment
          type: string
          description: Target environment for the job
          enum:
            - dev
            - staging
            - prod
        region:
          title: Region
          type: string
          description: Target AWS region
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
        waitForJob:
          title: Wait for completion
          type: boolean
          description: Wait for job to complete before finishing
          default: true

  steps:
    - id: rundeck-execute
      name: Execute Rundeck Job
      action: rundeck:job:execute
      input:
        jobId: dadc0afe-911b-4265-ba1f-5fe512cada39
        projectName: NA
        parameters:
          ENV: ${{ parameters.environment }}
          REGION: ${{ parameters.region }}
        waitForJob: ${{ parameters.waitForJob }}

  output:
    links:
      - title: Rundeck Execution
        url: ${{ steps['rundeck-execute'].output.executionId }}
        icon: dashboard
